#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PsychoPy presentation script generated by lexsync.

Design: {{DESIGN}}    Language: {{LANGUAGE}}
Conditions file: {{CONDITIONS_FILE}}

Each trial is rendered from a declarative list of events (``EVENTS``), so one
interpreter serves every paradigm. Onset triggers are written to the parallel
port on the exact flip on which their stimulus first appears, using
``win.callOnFlip``, the frame-locking that motivates lexsync. Stimulus
text is read as data from the conditions file at run time (never interpolated
into this code). When no parallel-port driver is present (a development machine,
macOS or continuous integration), a mock port prints the codes so the script
still runs end to end with no hardware.

Generated by lexsync; edit the design configuration rather than this file.
"""
import csv
import json
import os

from psychopy import visual, core, event, parallel

HERE = os.path.dirname(os.path.abspath(__file__))
CONDITIONS_FILE = os.path.join(HERE, "{{CONDITIONS_FILE}}")
TRIGGER_ADDRESS = {{TRIGGER_ADDRESS}}
RESET_AFTER_FRAMES = {{RESET_AFTER_FRAMES}}
INTER_TRIGGER_S = {{INTER_TRIGGER_S}}
FULLSCREEN = {{FULLSCREEN}}
WORD_FONT = "{{WORD_FONT}}"
BLOCK_START_TRIGGER = 254
BLOCK_END_TRIGGER = 255

# The trial event sequence (declarative data, written by lexsync).
EVENTS = json.loads(r"""{{EVENTS_JSON}}""")


class MockPort:
    """Stand-in used when no parallel-port driver is available."""

    def setData(self, data):
        print("[lexsync mock trigger] %d" % int(data))


def open_port(address):
    try:
        port = parallel.ParallelPort(address=address)
        port.setData(0)  # the dummy backend raises NotImplementedError here
        return port
    except Exception:
        return MockPort()


def load_trials(path):
    with open(path, newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def resolve_trigger(spec, trial):
    """A trigger spec is an int literal or '@column' naming a loop-table code."""
    if spec is None or spec == "":
        return None
    if isinstance(spec, str) and spec.startswith("@"):
        return int(trial[spec[1:]])
    return int(spec)


def show_frames(win, stim, frames, port, trigger):
    """Draw ``stim`` for ``frames`` flips; if a trigger is given, lock it to onset."""
    if trigger is not None:
        win.callOnFlip(port.setData, trigger)
    for f in range(frames):
        if stim is not None:
            stim.draw()
        win.flip()
        if trigger is not None and f == RESET_AFTER_FRAMES:
            win.callOnFlip(port.setData, 0)
    if trigger is not None and frames <= RESET_AFTER_FRAMES:
        port.setData(0)


def run_event(win, port, text_stim, ev, trial):
    etype = ev["type"]
    if etype in ("fixation", "text", "mask"):
        text_stim.text = trial[ev["field"]] if "field" in ev else ev.get("text", "")
        show_frames(win, text_stim, int(ev.get("frames", 1)), port,
                    resolve_trigger(ev.get("trigger"), trial))
    elif etype == "blank":
        show_frames(win, None, int(ev.get("frames", 1)), port, None)
    elif etype == "region":
        regions = [r for r in trial[ev["field"]].split(ev.get("sep", "|")) if r != ""]
        crit = int(trial.get("critical_region", 0) or 0)
        for i, region in enumerate(regions, start=1):
            text_stim.text = region
            trig = resolve_trigger(ev.get("crit_trigger"), trial) if i == crit else None
            if trig is not None:
                win.callOnFlip(port.setData, trig)
            text_stim.draw()
            win.flip()
            if trig is not None:
                core.wait(INTER_TRIGGER_S)
                port.setData(0)
            if event.waitKeys(keyList=[ev.get("key", "space"), "escape"]) == ["escape"]:
                return "escape"
    elif etype in ("response", "question"):
        if etype == "question":
            text_stim.text = trial.get(ev["field"], "")
            text_stim.draw()
        # A question presents its own prompt; a response draws nothing, so the same
        # flip clears the preceding stimulus, which therefore offsets at its own
        # duration rather than lingering for the whole response window.
        win.flip()
        keys = event.waitKeys(keyList=list(ev.get("keys", [])) + ["escape"],
                              maxWait=float(ev.get("timeout", 2.0)))
        if keys and "escape" in keys:
            return "escape"
    return None


def main():
    trials = load_trials(CONDITIONS_FILE)
    win = visual.Window(size=(1280, 1024), color="black", units="pix", fullscr=FULLSCREEN)
    port = open_port(TRIGGER_ADDRESS)
    text_stim = visual.TextStim(win, text="", height=48, color="white", font=WORD_FONT)

    win.callOnFlip(port.setData, BLOCK_START_TRIGGER)
    win.flip()
    port.setData(0)

    for trial in trials:
        stop = False
        for ev in EVENTS:
            if run_event(win, port, text_stim, ev, trial) == "escape":
                stop = True
                break
        if stop:
            break

    win.callOnFlip(port.setData, BLOCK_END_TRIGGER)
    win.flip()
    port.setData(0)
    win.close()
    core.quit()


if __name__ == "__main__":
    main()
